import type { Metadata } from "next";
import { Rethink_Sans } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { ourFileRouter } from "./api/uploadthing/core";
import { extractRouterConfig } from "uploadthing/server";
import { NextSSRPlugin } from "@uploadthing/react/next-ssr-plugin";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";
import { Analytics } from "@vercel/analytics/next";
import dynamic from "next/dynamic";
import { PHProvider } from "@/components/posthog-provider";
import { Suspense } from "react";

const inter = Rethink_Sans({ subsets: ["latin"], display: "swap" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PostHogPageView = dynamic(() => import("@/components/PostHogPageView"));

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <NextSSRPlugin routerConfig={extractRouterConfig(ourFileRouter)} />

        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Providers>
            <PHProvider>
              <Suspense>
                <PostHogPageView />
              </Suspense>
              {children}
            </PHProvider>

            <Toaster position="top-center" />
            <Analytics />
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
